name: LMSC-356

on:
  workflow_dispatch:
#  push:
#    paths-ignore:
#      - 'README.md'

jobs:
  build:
    runs-on: fae-emea-lnx-hw
    strategy:
      matrix:
        arch: ['bxarm:9.60.2', 'cxarm:9.60.3.6333-cap-max']
        wakeup: [wake, nowake]
    container:
      image: ghcr.io/fae-emea/${{ matrix.arch }}
    steps:      
      - name: Checkout project
        uses: actions/checkout@v4
      - if: matrix.wakeup == 'wake'
        name: Invoke the Arm compiler
        run: iccarm --version
      - name: CMake - Configure
        run: cmake -S. -Bbuild -GNinja
      - name: CMake - Build
        run: cmake --build build -j `nproc` --verbose